micronaut:
  application:
    name: micronaut_test
datasources:
  default:
    url: jdbc:postgresql://${POSTGRE_URL:localhost}:5432/docker
    driverClassName: org.postgresql.Driver
    username: docker
    password: docker
    schema-generate: CREATE
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        bytecode:
          provider: none
