micronaut:
  application:
    name: newtrywithdata
datasources:
  default:
    url: jdbc:postgresql://${POSTGRE_URL:localhost}:5432/postgres
    driverClassName: org.postgresql.Driver
    username: docker
    password: docker
    schema-generate: CREATE_DROP
#    dialect: org.hibernate.dialect.PostgreSQL95Dialect
jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        bytecode:
          provider: none
